### ISSUE TITLE
Instrumentation: Extras instrumentation

### ISSUE THREAD

**Issue by Cvalladares** [S2-group/NAPPA#4]
At the moment, instrumentation of extras is taking place by detecting calls to the putExtra() function.  In order to minimize the risk of losing extras during instrumentation,   then it is best to collect the extras on a single point rather than distribute them through all the putExtra(), putExtras(), and the entire family of extras injection.  The idea is to detect StartActivity() instead,  and to notify of all extras by the time an activity transitions rather than notifying every time an extra is added to a given intent. This also addresses the issue of removeExtra(), which is not yet dealt with.  Finally, this also makes sure we get the latest version of the extra.

To perform this task,  the plug-in instrumenter must be updated to search for startActivity instead.  Furthermore, a notifyExtras function must be developed in the prefetchinglib in order to be able to handle the notification of a list of extras.

**Comment by iivanoo** [comment]
Hi Christian,
yes we are aligned, please do the upgrade you just described and make a
pull request once it is done.

Cheers,

   Ivano

Il mer 1 mag 2019, 05:11 Cvalladares <notifications@github.com> ha scritto:

**Comment by Cvalladares** [comment]
I have managed to stabilize the plugin to instrument per call of StartActivity, as opposed to per extras.  The output messages have been updated as well.  Also,  

The plugin is able to handle two different scenarios:
A:
[startActivity(intentName);](https://github.com/S2-group/NAPPA/blob/1fb15ba2e4a1cd8e57bc0af60ee7738b779b1819/Plugin/test1/src/main/java/test/ExtrasInstrumentationAction.java#L105-L123)

B: 
[ViewName.getContext().startActivity(intentName);](https://github.com/S2-group/NAPPA/blob/1fb15ba2e4a1cd8e57bc0af60ee7738b779b1819/Plugin/test1/src/main/java/test/ExtrasInstrumentationAction.java#L126-L150)


There are certain things that the plugin instrumenter does not handle yet:
[startActivityForResult(pickContactIntent, PICK_CONTACT_REQUEST);](https://developer.android.com/training/basics/intents/result)

Overall,  the code to extend plugins was thoroughly documented in case further extensions must be made.  The files regarding the [Retrofit Instrumentation](https://github.com/S2-group/NAPPA/blob/1fb15ba2e4a1cd8e57bc0af60ee7738b779b1819/Plugin/test1/src/main/java/test/RetrofitInstrumentationAction.java#L1-L157) and the [Intent Instrumentation](https://github.com/S2-group/NAPPA/blob/1fb15ba2e4a1cd8e57bc0af60ee7738b779b1819/Plugin/test1/src/main/java/test/ExtrasInstrumentationAction.java#L1-L193) can serve as templates for any further extensions to the plugin.  

Finally,  a new compiled plugin jar file has been generated, to be used to add the plugin to Android Studio.  This can be found in the following directory: Plugin/test1/build/libs/test1-1.05-SNAPSHOT.jar

**Comment by Cvalladares** [comment]
There exists a particular edge case with the extras instrumentation taht must be fixed.  At the moment, this particular edge case does not let the projects compile, but is easily fixed as follows:

**Error Case:
`  PrefetchingLib.notifyExtras(Intent.createChooser.getExtras());
context.startActivity(Intent.createChooser(intent, "Send using"));`

**Fix:
` PrefetchingLib.notifyExtras(intent.getExtras());
context.startActivity(Intent.createChooser(intent, "Send using"))`

This has to do with the structure of the statement,  which is composed of a method within a method.   This can be fixed by looking into the PSI structure of such a statement, by using the psi viewer plugin for intellij.

**Comment by Cvalladares** [comment]
At the moment, Lambda expressions are not handled properly, given that by default a lambda expression cannot allow multiple statments, unless a block is defined.  This is the original statement:

`getActivity().findViewById(R.id.download_button).setOnClickListener(v -> startActivity(intent))`

Which becomes instrumented to the following:

`getActivity().findViewById(R.id.download_button).setOnClickListener(v -> PrefetchingLib.notifyExtras(intent.getExtras());startActivity(intent););
`
In order for the instrumentation to be correct, a block of statements must be defined instead.  Thus, multiple statements ins  single lambda function may take place.  At the moment this is done manually. 

`getActivity().findViewById(R.id.download_button).setOnClickListener(v -> {PrefetchingLib.notifyExtras(intent.getExtras());startActivity(intent);});`

Furthermore,  if the Intent and the extras are defined in a single line of code, while adding multiple extras,  two things happen:  **A)** a duplicate intent is created which contains the same extras, and **B)** All subsequent extras definitions are not captured. 

```
PrefetchingLib.notifyExtras(new Intent(SettingsActivity.this, PreferencesActivity.class)
                        .putExtra(PreferencesActivity.EXTRA_TITLE, R.string.display)
                        .putExtra.getExtras());
startActivity(new Intent(SettingsActivity.this, PreferencesActivity.class)
                        .putExtra(PreferencesActivity.EXTRA_TITLE, R.string.display)
                        .putExtra(PreferencesActivity.EXTRA_PREFERENCES, R.xml.preferences_display)));
```

The propper instrumentation is performed manually as follows:

```
      findViewById(R.id.drawer_display).setOnClickListener(v ->
        {
                PrefetchingLib.notifyExtras(new Intent(SettingsActivity.this, PreferencesActivity.class)
                        .putExtra(PreferencesActivity.EXTRA_TITLE, R.string.display)
                        .putExtra(PreferencesActivity.EXTRA_PREFERENCES, R.xml.preferences_display).getExtras());
        startActivity(new Intent(SettingsActivity.this, PreferencesActivity.class)
                        .putExtra(PreferencesActivity.EXTRA_TITLE, R.string.display)
                        .putExtra(PreferencesActivity.EXTRA_PREFERENCES, R.xml.preferences_display));
        });
```
