### ISSUE TITLE
OkHttp Interceptor: Null Response

### ISSUE THREAD

**Issue by Cvalladares** [S2-group/NAPPA#5]
There exists a risk that Responses that are **Prefetched** AND are still **fresh** in terms of time can return a null object, as can be seen in [Line 487](https://github.com/S2-group/NAPPA/blob/64e266092978bc2a3ddc20d6af1ebd388bbe0439/android_prefetching_lib/src/main/java/it/robertolaricchia/android_prefetching_lib/PrefetchingLib.java#L477-L491) of the code.  Given that the **intercept()** function is consumed from within okHttp inside a chain of interceptors,  it can be the case that the okhttp interceptor is not the last interceptor of the chain.  

The relevant code snippet consuming the response from within okhttp is as follows:

    RealInterceptorChain next = new RealInterceptorChain(interceptors, streamAllocation, httpCodec,
        connection, index + 1, request, call, eventListener, connectTimeout, readTimeout,
        writeTimeout);
    Interceptor interceptor = interceptors.get(index);
    Response response = interceptor.intercept(next);

    // Confirm that the next interceptor made its required call to chain.proceed().
    if (httpCodec != null && index + 1 < interceptors.size() && next.calls != 1) {
      throw new IllegalStateException("network interceptor " + interceptor
          + " must call proceed() exactly once");
    }

    // Confirm that the intercepted response isn't null.
    if (response == null) {
      throw new NullPointerException("interceptor " + interceptor + " returned null");
    }

    if (response.body() == null) {
      throw new IllegalStateException(
          "interceptor " + interceptor + " returned a response with no body");
    }

    return response;
`

On the scenario that a **null response** is generated, an exception may be thrown. I would like to look into this further to make sure that this does not introduce any unwanted behavior

**Comment by iivanoo** [comment]
Is it possible to check at run-time if the NAPPA interceptor is the last one in the chain and if not update the chain?

**Comment by Cvalladares** [comment]
Sorry, it seems like I raised false alarm.  I looked into usages of the "X-PREF" header everywhere else in the project, and it seems that this header is never set as part of the prefetching mechanism, or anywhere in the interceptor.  For this reason,  This block of code will never be executed, unless the "X-pref" http header is explicitly added as a header by an application.
